### ISSUE TITLE
[META] API V2 Tasks

### ISSUE THREAD

**Issue by yeastplume** [mimblewimble/grin-wallet#19]
Meta issue for work to support the new V2 API

- [x] Add doctests for every OwnerAPI method, OwnerAPI doctests will serve as jsonrpc documentation. See `OwnerAPI::accounts` for an example.
- [x] Add links to docs for APIOwner methods from each OwnerAPI method doc
- [ ] Implement fn initiate_tx(..) -> Result<(Slate, OutputLockFn<W, C, K>), Error> without using a callback
- [ ] Implement fn tx_lock_outputs(.. , mut lock_fn: OutputLockFn<W, C, K>) -> Result<(), Error> without using a callback
- [x] ~~Implement issue_send_tx like in refwallet/src/controller.rs~~ Edit: Would rather have consumers of the API calling all methods exactly as they are in the api, which now works with a bit more granularity than the legacy `issue_send_tx` (which does a bit too much)
- [ ] Either A) Depreciate APIOwner in favor of OwnerAPI, or B) Rename OwnerAPI to be more decriptive e.g. RPCAPIOwner
- [ ] Add ForeignAPI trait
- [x] Add jsonrpc_client macro for typed client generation
- [ ] Possibly automatically generate clients in other languages such as javascript
- [ ] Changes and refinements to the API itself (ongoing)

**Comment by yeastplume** [comment]
All done now, closing
