### ISSUE TITLE
Tracking issue for `full-wallet-lifecycle`

### ISSUE THREAD

**Issue by lehnberg** [mimblewimble/grin-wallet#212]
This is a tracking issue for `full-wallet-lifecycle`, https://github.com/mimblewimble/grin-rfcs/pull/18

#### Steps:
* [x] Add wallet initialisation through running `grin-wallet owner_api` or invoking the API directly from a linked binary.
* [x] Introduce SecureAPI mode as a v3 API
* [x] Modify workflow for Directly Linked Wallets
* [x] Introduce new Lifecycle API functions

#### Unresolved questions:

None so far

**Comment by lehnberg** [comment]
Assigned to you @yeastplume - feel free to make changes and update status as necessary!

**Comment by lehnberg** [comment]
🎉
